# PrimeTime BD Intel Global Settings
# Configuration file for the entire system

# System Configuration
system:
  name: "PrimeTime BD Intel"
  version: "1.0.0"
  environment: "development"  # development, staging, production
  timezone: "America/New_York"
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL

# Database Configuration
database:
  type: "postgresql"
  host: "localhost"
  port: 5432
  name: "n8n"
  user: "n8n_user"
  password: "${POSTGRES_PASSWORD}"
  pool_size: 10
  max_overflow: 20
  connection_timeout: 30

# Redis Configuration
redis:
  host: "localhost"
  port: 6379
  db: 0
  password: null
  max_connections: 20

# API Configuration
apis:
  openai:
    base_url: "https://api.openai.com/v1"
    model: "gpt-4-turbo-preview"
    max_tokens: 4000
    temperature: 0.1
    timeout: 60
  
  anthropic:
    base_url: "https://api.anthropic.com"
    model: "claude-3-sonnet-20240229"
    max_tokens: 4000
    temperature: 0.1
    timeout: 60
  
  serpapi:
    base_url: "https://serpapi.com/search"
    timeout: 30
  
  clearancejobs:
    base_url: "https://api.clearancejobs.com"
    timeout: 30

# Scraping Configuration
scraping:
  # Rate limiting
  requests_per_minute: 30
  delay_between_requests: 2.0  # seconds
  
  # User agents
  user_agents:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"
    - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36"
  
  # Proxy configuration
  use_proxies: false
  proxy_list: []
  
  # Retry configuration
  max_retries: 3
  retry_delay: 5.0  # seconds
  
  # Timeout configuration
  page_load_timeout: 30
  script_timeout: 30

# Job Processing Configuration
job_processing:
  # Batch processing
  batch_size: 100
  max_concurrent_jobs: 10
  
  # Data retention
  raw_data_retention_days: 90
  enriched_data_retention_days: 365
  processed_data_retention_days: 730
  
  # Quality thresholds
  min_confidence_score: 0.7
  min_relevance_score: 0.6

# Program Mapping Configuration
program_mapping:
  # Confidence thresholds
  exact_match_threshold: 0.95
  fuzzy_match_threshold: 0.8
  keyword_match_threshold: 0.6
  
  # Weighting factors
  title_weight: 0.4
  description_weight: 0.3
  company_weight: 0.2
  location_weight: 0.1
  
  # Program keywords
  program_keywords:
    GBSD: ["ICBM", "nuclear", "strategic deterrent", "Minuteman", "LGM-30", "LGM-35A"]
    NGAD: ["6th gen", "air dominance", "penetrating counter air", "F-X"]
    B-21: ["stealth bomber", "long range strike", "LRS-B", "Raider"]
    F-35: ["5th gen fighter", "JSF", "Lightning II", "stealth"]
    KC-46: ["aerial refueling", "tanker", "Pegasus", "KC-X"]
    T-7A: ["trainer", "Red Hawk", "T-X", "pilot training"]
    CH-53K: ["heavy lift", "King Stallion", "helicopter", "Marine Corps"]
    VH-92: ["presidential helicopter", "Marine One", "executive transport"]
    MQ-25: ["carrier-based", "UAV", "aerial refueling", "Stingray"]
    F_A_18: ["Super Hornet", "multi-role fighter", "carrier-based"]

# Organization Chart Configuration
org_chart:
  # Inference settings
  max_org_depth: 5
  min_confidence_score: 0.7
  
  # Relationship types
  relationship_types:
    - "reports_to"
    - "manages"
    - "peers"
    - "matrix_reports"
  
  # Title patterns
  title_patterns:
    director: ["Director", "Sr Director", "Executive Director"]
    manager: ["Manager", "Sr Manager", "Program Manager", "Project Manager"]
    lead: ["Lead", "Team Lead", "Technical Lead", "Engineering Lead"]
    senior: ["Senior", "Sr", "Principal", "Staff"]
    junior: ["Junior", "Jr", "Associate", "Entry"]

# Playbook Configuration
playbook:
  # Template settings
  default_template: "standard_playbook"
  custom_templates_dir: "./prompts/playbook_templates"
  
  # Content generation
  max_sections: 10
  max_bullet_points: 15
  include_contact_info: true
  include_company_background: true
  
  # Output formats
  output_formats:
    - "markdown"
    - "pdf"
    - "docx"
    - "html"

# Scoring Configuration
scoring:
  # Program scoring weights
  program_weights:
    contract_value: 0.3
    clearance_level: 0.25
    location_match: 0.2
    skill_match: 0.15
    company_reputation: 0.1
  
  # Clearance level scores
  clearance_scores:
    TS_SCI: 1.0
    TS: 0.8
    Secret: 0.6
    Confidential: 0.4
    None: 0.0
  
  # Location scoring
  location_scores:
    primary_state: 1.0
    secondary_state: 0.7
    clearance_hub: 0.9
    other: 0.3

# Notification Configuration
notifications:
  email:
    enabled: true
    smtp_host: "smtp.gmail.com"
    smtp_port: 587
    smtp_user: "${SMTP_USER}"
    smtp_password: "${SMTP_PASSWORD}"
    from_address: "noreply@primetime-bd-intel.com"
    to_addresses: []
  
  slack:
    enabled: false
    webhook_url: "${SLACK_WEBHOOK_URL}"
    channel: "#bd-intel"
  
  teams:
    enabled: false
    webhook_url: "${TEAMS_WEBHOOK_URL}"

# Monitoring Configuration
monitoring:
  # Metrics collection
  collect_metrics: true
  metrics_interval: 60  # seconds
  
  # Health checks
  health_check_interval: 300  # seconds
  health_check_timeout: 30  # seconds
  
  # Alerting
  alert_on_failure: true
  alert_on_warning: false
  
  # Logging
  log_retention_days: 30
  log_rotation_size: "100MB"

# Security Configuration
security:
  # Authentication
  require_auth: true
  session_timeout: 3600  # seconds
  
  # Data encryption
  encrypt_sensitive_data: true
  encryption_key: "${ENCRYPTION_KEY}"
  
  # API security
  rate_limit_enabled: true
  rate_limit_requests: 100
  rate_limit_window: 900  # seconds
  
  # Data access
  restrict_data_access: true
  allowed_ips: []
  allowed_domains: []

# Backup Configuration
backup:
  # Database backup
  db_backup_enabled: true
  db_backup_schedule: "0 2 * * *"  # Daily at 2 AM
  db_backup_retention: 30  # days
  
  # File backup
  file_backup_enabled: true
  file_backup_schedule: "0 3 * * *"  # Daily at 3 AM
  file_backup_retention: 90  # days
  
  # Backup storage
  backup_storage_type: "local"  # local, s3, gcs
  backup_storage_path: "./backups"
